/**
 * ===========================================================
 * TERMS LIST
 * ===========================================================
 * Each hype term has:
 *   - term: the actual word/phrase
 *   - explanation: why it's hype, vague, or subjective
 *
 * - for adjectives, consider adding adverb (amazing, amazingly)
 * - for verbs, consider 1st and 3rd person (shows, show)
 * - for compounds, consider with and withou hyphen (game changer, game-changer)
 */

window.hypeLessTerms = [
  { term: "advanced", explanation: "Buzzword; specify concrete technical contribution instead." },
  { term: "amazed", explanation: "Subjective emotional reaction; evaluation should come from readers, not authors." },
  { term: "amazing", explanation: "Subjective hype; avoid overstating importance." },
  { term: "amazingly", explanation: "Subjective exaggeration; let data speak for itself." },
  { term: "attractive", explanation: "Subjective judgment; prefer objective descriptors." },
  { term: "benchmark", explanation: "Often vague; specify exact standards, datasets, or comparisons." },
  { term: "best", explanation: "Absolute superlative; subjective and usually unverifiable." },
  { term: "best-in-class", explanation: "Marketing-style phrase; avoid in scientific writing." },
  { term: "beyond our expectation", explanation: "Subjective exaggeration; avoid overstating surprise." },
  { term: "break new ground", explanation: "Promotional phrase; describe the contribution factually instead." },
  { term: "breakthrough", explanation: "Strong hype implying major advance; use only if demonstrably established." },
  { term: "considerable", explanation: "Subjective emphasis; use precise, data-based statements instead." },
  { term: "considerably", explanation: "Subjective emphasis; use precise, data-based statements instead." },
  { term: "cutting edge", explanation: "Buzzword; specify concrete technical advance instead." },
  { term: "cutting-edge", explanation: "Buzzword; specify concrete technical advance instead." },
  { term: "easily", explanation: "Subjective simplification; better to specify actual efficiency or method." },
  { term: "elegant", explanation: "Subjective praise; evaluation should come from others." },
  { term: "elegantly", explanation: "Subjective praise; evaluation should come from others." },
  { term: "entirely", explanation: "Overstatement; avoid absolute claims." },
  { term: "essential", explanation: "Subjective praise; let readers judge importance." },
  { term: "exceptional", explanation: "Subjective hype; avoid evaluative language." },
  { term: "exceptionally", explanation: "Subjective exaggeration; avoid superlatives." },
  { term: "exciting", explanation: "Subjective judgment; keep tone factual." },
  { term: "excitingly", explanation: "Subjective judgment; keep tone factual." },
  { term: "excellent", explanation: "Subjective praise; use objective descriptors instead." },
  { term: "excellently", explanation: "Subjective praise; use objective descriptors instead." },
  { term: "extreme", explanation: "Exaggeration; use precise quantitative descriptors." },
  { term: "extremely", explanation: "Exaggeration; use precise quantitative descriptors." },
  { term: "extraordinary", explanation: "Subjective hype; avoid overstatement." },
  { term: "extraordinarily", explanation: "Subjective hype; avoid overstatement." },
  { term: "fantastic", explanation: "Subjective evaluation; avoid opinion." },
  { term: "fascinating", explanation: "Subjective evaluation; avoid opinion." },
  { term: "first", explanation: "Novelty claim; priority is contentious and often unverifiable." },
  { term: "fortunate", explanation: "Subjective praise; leave evaluation to others." },
  { term: "fortunately", explanation: "Subjective praise; leave evaluation to others." },
  { term: "fundamental", explanation: "Strong claim; avoid unless rigorously justified and demonstrable." },
  { term: "fundamentally", explanation: "Strong claim; avoid unless rigorously justified and demonstrable." },
  { term: "game changer", explanation: "Colloquial hype; avoid promotional phrasing." },
  { term: "game-changer", explanation: "Colloquial hype; avoid promotional phrasing." },
  { term: "game changing", explanation: "Colloquial hype; avoid promotional phrasing." },
  { term: "giant", explanation: "Vague descriptor; use precise quantitative terms instead." },
  { term: "great potential", explanation: "Speculative prediction; avoid hype about implications." },
  { term: "ground breaking", explanation: "Promotional; describe contribution concretely instead." },
  { term: "groundbreaking", explanation: "Promotional; describe contribution concretely instead." },
  { term: "high impact", explanation: "Promotional claim; show evidence rather than assert impact." },
  { term: "high-impact", explanation: "Promotional claim; show evidence rather than assert impact." },
  { term: "highest", explanation: "Superlative; requires explicit quantitative evidence." },
  { term: "holistic", explanation: "Buzzword; clarify the specific scope or dimensions considered." },
  { term: "holy grail", explanation: "Overblown metaphor; avoid in scientific writing." },
  { term: "ideal", explanation: "Absolute and subjective; avoid overstating." },
  { term: "ideally", explanation: "Absolute and subjective; avoid overstating." },
  { term: "impressive", explanation: "Subjective praise; leave evaluation to readers." },
  { term: "impressively", explanation: "Subjective praise; leave evaluation to readers." },
  { term: "important", explanation: "Subjective emphasis; use data-driven statements instead." },
  { term: "importantly", explanation: "Subjective emphasis; use data-driven statements instead." },
  { term: "incredible", explanation: "Subjective hype; let evidence speak instead." },
  { term: "incredibly", explanation: "Subjective exaggeration; avoid hyperbole." },
  { term: "impactful", explanation: "Buzzword; describe actual measured effects instead." },
  { term: "impactfully", explanation: "Buzzword; describe actual measured effects instead." },
  { term: "imperative", explanation: "Absolute and subjective; avoid overstating." },
  { term: "innovative", explanation: "Promotional claim; describe the actual contribution instead." },
  { term: "innovatively", explanation: "Promotional claim; describe the actual contribution instead." },
  { term: "innovation", explanation: "Promotional claim; describe the actual contribution instead." },
  { term: "interestingly", explanation: "Subjective reaction; avoid inserting author’s judgment." },
  { term: "key", explanation: "Subjective claim; avoid unless clearly defined." },
  { term: "landmark", explanation: "Strong hype; avoid promotional phrasing unless demonstrable." },
  { term: "leading", explanation: "Relative and subjective; specify exact comparative advantage." },
  { term: "lowest", explanation: "Superlative; requires clear quantitative evidence." },
  { term: "new", explanation: "Novelty should be evident from context, not asserted." },
  { term: "next generation", explanation: "Buzzword; specify exact advance instead." },
  { term: "next-generation", explanation: "Buzzword; specify exact advance instead." },
  { term: "next-gen", explanation: "Buzzword; specify exact advance instead." },
  { term: "no research has shown", explanation: "Unprovable novelty claim; avoid unverifiable statements." },
  { term: "notably", explanation: "Subjective emphasis; use factual descriptors instead." },
  { term: "novel", explanation: "Novelty should be evident from context, not asserted." },
  { term: "open new avenues", explanation: "Promotional phrase; describe implications concretely instead." },
  { term: "open the window", explanation: "Vague metaphor; avoid unclear imagery." },
  { term: "open up a splendid era", explanation: "Promotional and vague metaphor; avoid exaggeration." },
  { term: "open up new avenues", explanation: "Promotional phrase; describe implications concretely instead." },
  { term: "opens new avenues", explanation: "Promotional phrase; describe implications concretely instead." },
  { term: "opens the window", explanation: "Vague metaphor; avoid unclear imagery." },
  { term: "opens up a splendid era", explanation: "Promotional and vague metaphor; avoid exaggeration." },
  { term: "opens up new avenues", explanation: "Promotional phrase; describe implications concretely instead." },
  { term: "outstanding", explanation: "Subjective praise; avoid evaluative language." },
  { term: "paramount", explanation: "Exaggeration; use precise quantitative descriptors." },
  { term: "paradigm shift", explanation: "Strong claim implying fundamental change; avoid unless demonstrable." },
  { term: "paradigm-shift", explanation: "Strong claim implying fundamental change; avoid unless demonstrable." },
  { term: "paradigm shifting", explanation: "Strong claim implying fundamental change; avoid unless demonstrable." },
  { term: "paradigm-shifting", explanation: "Strong claim implying fundamental change; avoid unless demonstrable." },
  { term: "pave the way", explanation: "Promotional metaphor; describe contribution directly." },
  { term: "paves the way", explanation: "Promotional metaphor; describe contribution directly." },
  { term: "powerful", explanation: "Subjective; describe actual effect size or mechanism." },
  { term: "powerfully", explanation: "Subjective; describe actual effect size or mechanism." },
  { term: "promising", explanation: "Speculative hype; describe supporting evidence instead." },
  { term: "profound", explanation: "Overstatement; prefer precise description of scope or magnitude." },
  { term: "record", explanation: "Potential hype; use only with clear quantitative context." },
  { term: "remarkable", explanation: "Subjective evaluation; let evidence speak." },
  { term: "remarkably", explanation: "Subjective evaluation; let evidence speak." },
  { term: "revolutionary", explanation: "Promotional claim; avoid unless demonstrable." },
  { term: "significant", explanation: "Ambiguous; use precise statistical or substantive meaning." },
  { term: "significantly", explanation: "Ambiguous; use precise statistical or substantive meaning." },
  { term: "state-of-the-art", explanation: "Buzzword; specify concrete technical advances instead." },
  { term: "straightforward", explanation: "Subjective simplification; describe actual steps or methods." },
  { term: "strikingly", explanation: "Subjective emphasis; avoid hype." },
  { term: "stunning", explanation: "Exaggerated hype term; avoid overstatement." },
  { term: "strongest", explanation: "Superlative; requires explicit evidence." },
  { term: "successful", explanation: "Subjective; describe results factually instead." },
  { term: "successfully", explanation: "Subjective; simply state what was achieved." },
  { term: "surprisingly", explanation: "Subjective reaction; describe results factually instead." },
  { term: "to the best of our knowledge", explanation: "Often unnecessary hedging; use precise claims." },
  { term: "transformative", explanation: "Promotional; describe specific impact instead." },
  { term: "tremendous", explanation: "Exaggerated hype; avoid overstatement." },
  { term: "ultra", explanation: "Promotional exaggeration; avoid hype prefixes." },
  { term: "ultimate", explanation: "Overstated finality; avoid absolutes." },
  { term: "unconventional", explanation: "Vague novelty claim; describe concrete differences instead." },
  { term: "unexpectedly", explanation: "Subjective reaction; describe results factually instead." },
  { term: "unique", explanation: "Absolute claim; avoid unless objectively defined." },
  { term: "uniquely", explanation: "Absolute claim; avoid unless objectively defined." },
  { term: "unmatched", explanation: "Absolute promotional claim; avoid." },
  { term: "unparalleled", explanation: "Absolute promotional claim; avoid." },
  { term: "unprecedented", explanation: "Overused novelty claim; avoid unless rigorously justified." },
  { term: "unprecedentedly", explanation: "Adverb form of 'unprecedented'; same caution applies." },
  { term: "unrivaled", explanation: "Absolute promotional claim; avoid." },
  { term: "valuable contribution", explanation: "Subjective praise; evaluation should be left to readers." },
  { term: "vast", explanation: "Exaggerated; specify magnitude with data." },
  { term: "vast opportunities", explanation: "Exaggerated; describe specific potential instead." },
  { term: "widespread", explanation: "Overstatement; quantify scope with data instead." }
];


/**
 * Exceptions list
 * These are phrases that should NOT be flagged,
 * even though they contain hype words.
 */
window.hypeLessExceptions = [
  "first-principles",
  "unique identifier",
  "to record",
  "recording",
  "benchmark experiment",
  "benchmark test",
  "first step",
  "First,",
  "firstly",
  "first-order",
  "leading to",
  "we first",
  "best practice",
  "New Zealand",
  "lowest unoccupied molecular orbital",
  "highest occupied molecular orbital",
  "extreme value theory"// Add more if needed
];

